url: "https://your-name.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "harshkaso.github.io" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
